#!/usr/bin/bash

# delay until the drawing is finished
sleep 100

# get weathermap process ID
weathermapProcess=$(ps -aef | grep weathermap/weathermap)
set ${weathermapProcess}
weathermapProcessID=$2

# get WebKitWebProcess ID
pgrep=$(pgrep -lP ${weathermapProcessID})
set ${pgrep}
WebKitWebProcesID=$3

# call cpulimit
cpulimit -l 5 -p ${WebKitWebProcesID}
