#!/usr/bin/bash

# get weathermap process ID
#weathermapProcess=$(ps -aef | grep weathermap/weathermap)
# pi        1286     1  7 16:51 ?        00:05:46 /home/pi/github/weathermap/weathermap
weathermapProcess=$(ps --no-header -C weathermap)
#  1286 ?        00:05:31 weathermap
set ${weathermapProcess}

#echo $6
echo $1
#echo $8
echo $4

#if [ "$6" = "?" ]; then
if [ "$2" = "?" ]; then # Since the TTY is "?", this is the service
  # delay until the drawing is finished
  sleep 100

#  weathermapProcessID=$2
  weathermapProcessID=$1

  # get WebKitWebProcess ID
  pgrep=$(pgrep -lP ${weathermapProcessID})
  set ${pgrep}
  WebKitWebProcesID=$3

  # call cpulimit
  cpulimit -l 50 -p ${WebKitWebProcesID}
fi
